---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm_chart.configmapName" . }}
  labels:
    {{- include "helm_chart.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.idMapperAppProperties }}
  {{ $path }}: |
{{ $config | indent 4 }}
{{- end -}}