{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helm_chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $labels := include "helm_chart.labels" . | nindent 4 }}
{{- range $path := tuple "a" "b" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $path }}
  labels:
    {{- $labels }}
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  tls:
    - hosts:
      {{- if eq $path "a" }}
      {{- range $.Values.ingress.tls.hostsA }}
      - {{ . }}
      {{- end }}
      {{ else }}
      {{- range $.Values.ingress.tls.hostsB }}
      - {{ . }}
      {{- end }}
      {{- end }}
      secretName: {{ $.Values.ingress.tls.secretName }}-{{ $path }}
  rules:
    {{- if eq $path "a" }}
    {{- range $.Values.ingress.hostsA }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}-{{ $path }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
    {{ else }}
    {{- range $.Values.ingress.hostsB }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}-{{ $path }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
