apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: default
  annotations:
    ingress.class: "haproxy"
    haproxy.org/path-rewrite: "/"
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" #important
#    nginx.ingress.kubernetes.io/enable-access-log: "true"
#    nginx.ingress.kubernetes.io/access-log-format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"'
#    nginx.ingress.kubernetes.io/server-snippet: |
#      access_log /var/log/nginx/west-haproxy.log;
spec:
  rules:
    - #host: {{ .Chart.Name }}.k8s.rcsb.org
      http:
        paths:
          - path: /{{ .Chart.Name }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: 9000