apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.http_port }}
      targetPort: {{ .Values.http_port }}
    - name: rsocket
      protocol: TCP
      port: {{ .Values.rsocket_port }}
      targetPort: {{ .Values.rsocket_port }}