name: Push2Branch

on:
  push:
    branches-ignore:
      - "master"

jobs:
  push-to-branch:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/push-to-branch.yaml@master
    with:
      distribution: "${{ github.ref_name }}_idmapper"
      type: "jar"