name: PushTestContainer

on:
  push:
    branches:
      - "master"

jobs:
  build-test-container:
    runs-on:
      - self-hosted
      - java
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push via jib
        run: |
          mvn package jib:build -Ptest-container --no-transfer-progress -Dmaven.test.skip=true