name: Run CI/CD Workflow

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - 'k8s/**'
  workflow_dispatch:
  # Wait on push-to-master workflow (that calls release within it) so that there's no race condition in pushing to harbor
  workflow_run:
    workflows:
      - 'Push2Master'

jobs:
  run-workflow:
    name: "Run automated workflow"
    uses: rcsb/devops-cicd-github-actions/.github/workflows/workflow-java.yaml@master
    with:
      mainline_branch: master
