name: Run CI/CD Workflow

on:
  push:
    paths-ignore:
      - "k8s/**"
  workflow_dispatch:

jobs:
  run-workflow:
    name: "Run automated workflow"
    uses: rcsb/devops-cicd-github-actions/.github/workflows/workflow-java.yaml@master
    with:
      do_production_build: true