name: Run CI/CD Workflow

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'k8s/**'

jobs:
  run-workflow:
    name: "Run automated workflow"
    uses: rcsb/devops-cicd-github-actions/.github/workflows/workflow-java.yaml@master
    with:
      mainline_branch: master
